version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: online-exam-db
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_password
      POSTGRES_DB: online_exam_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: online-exam-redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
